### ISSUE TITLE
Pydantic 1.10.3 incompatible with typing-extensions 4.1.1

### ISSUE THREAD

**Issue by hsheth2** [pydantic/pydantic#4885]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

- Installed latest pydantic and typing-extensions 4.1.1
- Code crashes on `import pydantic`

I suspect we just need to bump the min version requirement or fix a cross-version incompatibility, since it works with typing-extensions 4.4.0.

### Example Code

```Python
# Set up a clean venv
# pip install pydantic==1.10.3 typing-extensions==4.1.1

>>> import pydantic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 46, in init pydantic.dataclasses
    # | None    | Attribute is set to None.               |
  File "pydantic/main.py", line 121, in init pydantic.main
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'
```

### Python, Pydantic & OS Version

```Text
Crashes so I can't run that

Tested with python 3.7.9
```

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Grrr, good catch, sorry I didn't see this before.

PR welcome to fix this.

**Comment by samuelcolvin** [comment]
See #4886

**Comment by adrianeboyd** [comment]
On behalf of spacy-related packages: would it be possible for you to temporarily yank v1.10.3?

To address this and be compatible with v1.10.4, we'd have to release new versions of a whole series of packages and nearly everyone (including me) is currently on vacation. Even if v1.10.4 is released with a fix, pip would still back off to v1.10.3 for `spacy`, etc. because of its current pins for `typing_extensions`. If it could instead back off to v1.10.2, we'd have a bit more breathing room to make the updates on our end.

**Comment by samuelcolvin** [comment]
I'll make a new release of v1.10.4 today, I think that's better.

Sorry again for the inconvenience.

**Comment by samuelcolvin** [comment]
Humm, just read your message fully 🙈.

Okay, unless @hramezani or @PrettyWood have a problem, I'll yank v1.10.3.

Once that's done, do you have a problem with me releasing v1.10.4 with just this fixed?

**Comment by adrianeboyd** [comment]
Thanks for the quick response! I don't think that a v1.10.4 release with the updated requirements should cause any problems on our end (and would be used for python 3.8+).

**Comment by samuelcolvin** [comment]
v1.10.3 has been yanked.

**Comment by samuelcolvin** [comment]
v1.10.4 is building now.

**Comment by kjozef-work** [comment]
we do see the same error with 1.10.4  still
 `Downloading pydantic-1.10.4-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)`

**Comment by samuelcolvin** [comment]
Have you checked the content of that wheel (it's just a zip file)? It should be correct.

**Comment by kjozef-work** [comment]
apologize for not providing details - pydantic 1.10.4 fails still on python 3.8 with typing-extensions 4.1.1 , it passes though on python 3.7 with te-4.1.1

**Comment by samuelcolvin** [comment]
Yes, that's why we changed the minimum allowed version in dependencies

https://github.com/pydantic/pydantic/blob/63c683d9fc7b494bf81e964f97ec2f9b78b8e09d/setup.py#L133

Please review the release details.

**Comment by Hunterlige** [comment]
Hello,

The pydantic release on conda does not enforce `typing-extensions>=4.2.0` and cause the same error:
`TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'`
https://github.com/conda-forge/pydantic-feedstock/blob/main/recipe/meta.yaml#L30

**Comment by samuelcolvin** [comment]
Thanks for reporting, I thought the bot auto updated that, apparently not.

I'll check tomorrow if I can update it without having to create another patch release.

**Comment by samuelcolvin** [comment]
> Hello,
> 
> The pydantic release on conda does not enforce `typing-extensions>=4.2.0` and cause the same error: `TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'` https://github.com/conda-forge/pydantic-feedstock/blob/main/recipe/meta.yaml#L30

See https://github.com/conda-forge/pydantic-feedstock/pull/73
