### ISSUE TITLE
Attribute error using `model_validator` inside of spark job

### ISSUE THREAD

**Issue by bboe** [pydantic/pydantic#12794]
### Initial Checks

- [x] I confirm that I'm using Pydantic V2

### Description

The following code results in the exception `AttributeError: 'Package' object has no attribute 'attribute'` when executed in the pyspark worker.

Environment versions:
pydantic version: 2.12.5
pyspark version: 4.1.1

This code worked fine in pydantic `2.10.6` and appears to have stopped working in `2.11+`

```
pydantic version: 2.10.6
pyspark version: 4.1.1
[Package(attribute='a')]
[Package(attribute='ab'), Package(attribute='bc')]   
```

### Example Code

```Python
import pydantic
import pyspark
from pydantic import (
    BaseModel,
    ConfigDict,
    field_validator,
    model_validator,
)
from pyspark.sql import SparkSession

print(f"pydantic version: {pydantic.__version__}")
print(f"pyspark version: {pyspark.__version__}")


class Package(BaseModel):
    attribute: str

    @model_validator(mode="after")
    def validate_model(self):
        assert self.attribute
        return self


def create_package(attributes):
    return [Package(attribute=attribute) for attribute in attributes]


print(create_package(["a"]))  # Works without spark

spark = SparkSession.builder.getOrCreate()
results = spark.sparkContext.parallelize(["ab", "bc"], 2).mapPartitions(create_package)
print(results.collect())  # Fails
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.12.5
        pydantic-core version: 2.41.5
          pydantic-core build: profile=release pgo=false
               python version: 3.10.19 (main, Oct 10 2025, 08:06:26) [Clang 17.0.0 (clang-1700.0.13.3)]
                     platform: macOS-15.7.3-arm64-arm-64bit
             related packages: typing_extensions-4.15.0
                       commit: unknown
```

cc @hawaiigal

**Comment by bboe** [comment]
It would seem that this behavior actually broke in pydantic-core 2.29.0.

```
.venv ❯ pip list | grep pydantic         
pydantic                               2.10.6
pydantic_core                          2.28.0

~
.venv ❯ python pydantic_test.py          
pydantic version: 2.10.6
pyspark version: 4.1.1
[Package(attribute='a')]
[Package(attribute='ab'), Package(attribute='bc')]
```


After force installing 2.29.0
```
.venv ❯ pip list | grep pydantic         
pydantic                               2.10.6
pydantic_core                          2.29.0

~
.venv ❯ python pydantic_test.py          
pydantic version: 2.10.6
pyspark version: 4.1.1
[Package(attribute='a')]
26/02/10 13:36:21 ERROR Executor: Exception in task 1.0 in stage 0.0 (TID 1)/ 2]
...
AttributeError: 'Package' object has no attribute 'attribute'
```

**Comment by andresliszt** [comment]
Interesting — this happens because PySpark, when running parallel jobs, needs to serialize/deserialize using `pickle`.
I was able to reproduce the same error locally inside a Docker image. The attribute `__dict__ ` is empty when pydantic tries to apply the validator inside the worker. Note that with mode=before it works.

By the way, I would not use complex types in pyspark. Just builtins or Spark types.
```python
spark = (
    SparkSession.builder
    .appName("example")
    .master("local[*]")
    .getOrCreate()
)

class Package(BaseModel):
    attribute: str

    @model_validator(mode="after")
    def validate_model(self):
        if self.__dict__ == {}:
            raise RuntimeError("Something weird")
        assert self.attribute
        return self


def create_package(attributes):
    return [Package(attribute=attribute) for attribute in attributes]


>>> results = spark.sparkContext.parallelize(["ab", "bc"], 2).mapPartitions(create_package).collect()
RuntimeError: Something weird
```

**Comment by Viicos** [comment]
Can you try with pydantic installed from `main`? Something similar was recently fixed (https://github.com/pydantic/pydantic/issues/12696).

**Comment by bboe** [comment]
> Can you try with pydantic installed from main?

My test resulted in a different error with that version:

```
.venv ❯ pip list | grep pydantic

pydantic                               2.13.0a0+dev
pydantic_core                          2.41.5

~/Desktop
.venv ❯ 

~/Desktop
.venv ❯ python pydantic_test.py 
pydantic version: 2.13.0a0+dev
pyspark version: 4.1.1
Traceback (most recent call last):
  File "/Users/bboe/Desktop/pydantic_test.py", line 15, in <module>
    class Package(BaseModel):
  File "/Users/bboe/src/vulcan/.venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 256, in __new__
    complete_model_class(
  File "/Users/bboe/src/vulcan/.venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 684, in complete_model_class
    cls.__pydantic_validator__ = create_schema_validator(
  File "/Users/bboe/src/vulcan/.venv/lib/python3.10/site-packages/pydantic/plugin/_schema_validator.py", line 53, in create_schema_validator
    return SchemaValidator(schema, config, _use_prebuilt=_use_prebuilt)
TypeError: SchemaValidator.__new__() got an unexpected keyword argument '_use_prebuilt'
```

It's worth noting, however, that I get that error without using pyspark so perhaps there's a separate bug in the main branch or in how I'm installing from the branch `pip install https://github.com/pydantic/pydantic-core/archive/main.zip`.

**Comment by bboe** [comment]
Following a similar approach from #12696, the following two files demonstrate the problem without using pyspark.

pydantic_test_dump.py
```python
import cloudpickle
import pydantic
import pydantic_core
from pydantic import BaseModel, model_validator

class Package(BaseModel):
    attribute: str

    @model_validator(mode="after")
    def validate_model(self):
        assert self.attribute
        return self


if __name__ == "__main__":
    print(f"  cloudpickle version: {cloudpickle.__version__}")
    print(f"     pydantic version: {pydantic.__version__}")
    print(f"pydantic_core version: {pydantic_core.__version__}")

    with open("package.pkl", "wb") as fp:
        cloudpickle.dump(Package, fp)
```

pydantic_test_load.py
```python
import cloudpickle


if __name__ == "__main__":
    with open("package.pkl", "rb") as fp:
        Package = cloudpickle.load(fp)

    print(Package(attribute="a"))
```

Execution:

```
tmpvenv ❯ python pydantic_test_dump.py 
  cloudpickle version: 3.1.2
     pydantic version: 2.12.5
pydantic_core version: 2.41.5

~/Desktop
tmpvenv ❯ python pydantic_test_load.py 
Traceback (most recent call last):
  File "/Users/bboe/Desktop/pydantic_test_load.py", line 8, in <module>
    print(Package(attribute="a"))
  File "/Users/bboe/Desktop/tmpvenv/lib/python3.10/site-packages/pydantic/main.py", line 250, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/Users/bboe/Desktop/pydantic_test_dump.py", line 11, in validate_model
    assert self.attribute
  File "/Users/bboe/Desktop/tmpvenv/lib/python3.10/site-packages/pydantic/main.py", line 1026, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Package' object has no attribute 'attribute'
```

**Comment by Viicos** [comment]
> My test resulted in a different error with that version:

Sorry this is because you also need to install `pydantic-core` from `main` (which requires a Rust toolchain).

Thanks for providing the repro without pyspark. I was able to confirm it is fixed on `main`, so this is the same as https://github.com/pydantic/pydantic/issues/12696. We'll be releasing a 2.13 beta really soon.
