### ISSUE TITLE
"Unexpected keyword argument" when using `ConfigDict(extra="forbid")`

### ISSUE THREAD

**Issue by dfarley1** [pydantic/pydantic#8954]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using `ConfigDict(extra="forbid")`, mypy complains about "Unexpected keyword argument" for all fields on a model, but only if one of the fields is `Optional[]` with a single type.

As shown in the example below, if `thing` is `str | None` or `Optional[int]` then we get mypy errors, but `str | int | None` is totally fine?

This worked fine with Pydantic 2.5.3, but I don't see anything potentially related in the changelog since then.

### Example Code

```Python
from pydantic import BaseModel as _BaseModel
from pydantic import ConfigDict
from typing import Optional


class BaseModel(_BaseModel):
    model_config = ConfigDict(extra="forbid")


class Broken1(BaseModel):
    thing: str | None


class Broken2(BaseModel):
    thing: Optional[int]


class Works1(BaseModel):
    thing: str


class Works2(BaseModel):
    thing: str | int | None


broken1 = Broken1(thing="") # <--- Unexpected keyword argument "thing" for "Broken" Mypy (call-arg)
broken2 = Broken2(thing=5) # <--- Unexpected keyword argument "thing" for "Broken" Mypy (call-arg)
works1 = Works1(thing="")
works2 = Works2(thing=7)
```

### Python, Pydantic & OS Version

```Text
$ python --version
Python 3.10.12

$ mypy --version
mypy 1.8.0 (compiled: yes)

$ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.6.3
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /usr/local/lib/python3.10/dist-packages/pydantic
               python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
                     platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.35
             related packages: mypy-1.8.0 typing_extensions-4.10.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@dfarley1,

Thanks for reporting this. That does seem quite odd. Let's get @dmontagu on the case.

**Comment by dmontagu** [comment]
I am able to reproduce this in v2.6.3, but not on main, so I think it should be fixed in the next pydantic release. @sydney-runkle will know when that is likely to be!

**Comment by sydney-runkle** [comment]
Should be fixed now in `2.6.4` :)
