### ISSUE TITLE
[V2] model_dump(exclude_unset=True) fails for dataclasses

### ISSUE THREAD

**Issue by andriilahuta** [pydantic/pydantic#5527]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

The code example raises `AttributeError: 'Foo' object has no attribute '__pydantic_fields_set__'`.

### Example Code

```Python
from dataclasses import dataclass
from pydantic import BaseModel

@dataclass
class Foo:
    val: str

class Bar(BaseModel):
    foo: Foo

Bar(foo=Foo(val='baz')).model_dump(exclude_unset=True)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a2
        pydantic-core version: 0.24.1 release build profile
                 install path: C:\Program Files\Python\Lib\site-packages\pydantic
               python version: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by hramezani** [comment]
Thanks @andriilahuta for reporting this.

I can confirm the problem in `2.0a3` and `pydantic-core==0.25.0`. 

I think it happens because of `exclude_unset=True` and probably it has to be fixed in `pydantic-core`

**Comment by dmontagu** [comment]
The code sample submitted here works in v2.0b3, so I'll close this now. Please let us know if you run into any similar issues.
