### PR TITLE
Fix missing recursive_guard parameter in Pydantic v1 for python 3.12.4+

### PR DESCRIPTION
**Pull request by ellyx13**
## Change Summary

I add args recursive guard=set() when calling evaluate function because in python 3.12 they don't add default value for this params. You can [see that here](https://github.com/sobolevn/cpython/commit/d7483de262e53059671946b147c1fe62986582c7).

While waiting for this merge request to be accepted, you can quickly fix it by using python version 3.12.3

## Related issue number

fix https://github.com/pydantic/pydantic/issues/9609 and fix https://github.com/pydantic/pydantic/issues/9607

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [ ] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Skip change file check

### CODE REVIEW

File: pydantic/v1/typing.py [hunk 1]
```diff
@@ -54,17 +54,21 @@
...
         # Even though it is the right signature for python 3.9, mypy complains with
         # `error: Too many arguments for "_evaluate" of "ForwardRef"` hence the cast...
         return cast(Any, type_)._evaluate(globalns, localns, set())
 
+else:
+    def evaluate_forwardref(type_: ForwardRef, globalns: Any, localns: Any) -> Any:
+        # For 3.12.4+ provide a default `recursive_guard` to resolve:
+        # TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
+        return cast(Any, type_)._evaluate(globalns, localns, set(), recursive_guard=set())
+
```
Comment (vfazio) [inline pydantic/v1/typing.py:71]: I think I made a mistake when i glanced at the code earlier. That's what i get when i do things in a rush.

Python 3.12.4 has this commit:

```
vfazio@Zephyrus:~/development/cpython$ git describe --contains 5430f614371530aab1178b3b610add4bf54c383e
v3.12.4~194
```
Which is: https://github.com/python/cpython/pull/118104

Which changed the function signature of `ForwardRef._evaluate` to force `recursive_guard` to be a kwarg

```python
def _evaluate(self, globalns, localns, type_params=None, *, recursive_guard):
```


The fixup should maybe be:

```
if sys.version_info < (3, 9):

    def evaluate_forwardref(type_: ForwardRef, globalns: Any, localns: Any) -> Any:
        return type_._evaluate(globalns, localns)

else:
    def evaluate_forwardref(type_: ForwardRef, globalns: Any, localns: Any) -> Any:
        # Even though it is the right signature for python 3.9, mypy complains with
        # `error: Too many arguments for "_evaluate" of "ForwardRef"` hence the cast...
        # Note 3.13/3.12.4+ made `recursive_guard` a kwarg, so name it explicitly to avoid:
        # TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
        return cast(Any, type_)._evaluate(globalns, localns, recursive_guard=set())
```

The syntax should work on previous versions (pre 3.12.4/3.13) and also work for the new kwarg status.

The extra `set()` is unnecessary and is actually overwriting the default value for `type_params`.

Anyway, totally untested, but my thoughts

Comment (ellyx13) [reply pydantic/v1/typing.py:71]: > I think I made a mistake when i glanced at the code earlier. That's what i get when i do things in a rush.
> 
> Python 3.12.4 has this commit:
> 
> ```
> vfazio@Zephyrus:~/development/cpython$ git describe --contains 5430f614371530aab1178b3b610add4bf54c383e
> v3.12.4~194
> ```
> 
> Which is: [python/cpython#118104](https://github.com/python/cpython/pull/118104)
> 
> Which changed the function signature of `ForwardRef._evaluate` to force `recursive_guard` to be a kwarg
> 
> ```python
> def _evaluate(self, globalns, localns, type_params=None, *, recursive_guard):
> ```
> 
> ```python
> >>> inspect.signature(typing.ForwardRef._evaluate).parameters['recursive_guard'].kind
> <_ParameterKind.KEYWORD_ONLY: 3>
> ```
> 
> The fixup should maybe be:
> 
> ```
> if sys.version_info < (3, 9):
> 
>     def evaluate_forwardref(type_: ForwardRef, globalns: Any, localns: Any) -> Any:
>         return type_._evaluate(globalns, localns)
> 
> else:
>     def evaluate_forwardref(type_: ForwardRef, globalns: Any, localns: Any) -> Any:
>         # Even though it is the right signature for python 3.9, mypy complains with
>         # `error: Too many arguments for "_evaluate" of "ForwardRef"` hence the cast...
>         # Note 3.13/3.12.4+ made `recursive_guard` a kwarg, so name it explicitly to avoid:
>         # TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
>         return cast(Any, type_)._evaluate(globalns, localns, recursive_guard=set())
> ```
> 
> The syntax should work on previous versions (pre 3.12.4/3.13) and also work for the new kwarg status.
> 
> The extra `set()` is unnecessary and is actually overwriting the default value for `type_params`.
> 
> Anyway, totally untested, but my thoughts

Is it just that I need to run tests on all python versions to make sure it's correct? Can you guide me, because I really want to fix this error, thank you.

Comment (sydney-runkle) [inline pydantic/v1/typing.py:71]:
```suggestion
else:
    def evaluate_forwardref(type_: ForwardRef, globalns: Any, localns: Any) -> Any:
        # For 3.12.4+ provide a default `recursive_guard` to resolve:
        # TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
        return cast(Any, type_)._evaluate(globalns, localns, set(), recursive_guard=set())
```

File: pydantic/v1/typing.py [hunk 2]
```diff
@@ -54,17 +54,21 @@
...
     def evaluate_forwardref(type_: ForwardRef, globalns: Any, localns: Any) -> Any:
         # Even though it is the right signature for python 3.9, mypy complains with
         # `error: Too many arguments for "_evaluate" of "ForwardRef"` hence the cast...
         return cast(Any, type_)._evaluate(globalns, localns, set())
 
+else:
+    def evaluate_forwardref(type_: ForwardRef, globalns: Any, localns: Any) -> Any:
+        # For 3.12.4+ provide a default `recursive_guard` to resolve:
+        # TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
+        return cast(Any, type_)._evaluate(globalns, localns, set(), recursive_guard=set())
```
Comment (sydney-runkle) [inline pydantic/v1/typing.py:70]:
```suggestion
else:
    def evaluate_forwardref(type_: ForwardRef, globalns: Any, localns: Any) -> Any:
        # Even though it is the right signature for python 3.9, mypy complains with
        # `error: Too many arguments for "_evaluate" of "ForwardRef"` hence the cast...
        # Note 3.13/3.12.4+ made `recursive_guard` a kwarg, so name it explicitly to avoid:
        # TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
        return cast(Any, type_)._evaluate(globalns, localns, recursive_guard=set())
```

Comment (sydney-runkle) [reply pydantic/v1/typing.py:70]: Going to try this more simple approach, thanks @vfazio!

**Comment by sydney-runkle** [comment]
@ellyx13,

This change looks great. Could you please create a branch from `v1.10.X-fixes`, add this change, then open a PR against `v1.10.X` fixes instead? We'll want to merge it there to get it into our next V1 release, and we'll pull that into our next V2 release as well under the V1 namespace.

**Comment by vfazio** [comment]
> @ellyx13,
> 
> This change looks great. Could you please create a branch from `v1.10.X-fixes`, add this change, then open a PR against `v1.10.X` fixes instead? We'll want to merge it there to get it into our next V1 release, and we'll pull that into our next V2 release as well under the V1 namespace.

If this hasn't been done by tomorrow AM, I'll make a PR. This issue is preventing us from taking 3.12.4 so I'd like to see this fixed.

**Comment by ellyx13** [comment]
> @ellyx13,
> 
> This change looks great. Could you please create a branch from `v1.10.X-fixes`, add this change, then open a PR against `v1.10.X` fixes instead? We'll want to merge it there to get it into our next V1 release, and we'll pull that into our next V2 release as well under the V1 namespace.

I will do it now

**Comment by allex083** [comment]
HI all, I'm just running into this error: File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/v1/typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pydantic/v1/typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'.


pydantic version is 3.6.1 and my Python version is 3.12.4.

How can I fix this error? SOS~~ THANKS
