### ISSUE TITLE
not compatible with python 3.7.1

### ISSUE THREAD

**Issue by hampusek** [pydantic/pydantic#6426]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Using pydantic `BaseModel` or `dataclass` in python 3.7.1 causes the following error:

```
AttributeError: module 'typing' has no attribute 'OrderedDict'
```

complete error log:

```
Traceback (most recent call last):
  File "t.py", line 5, in <module>
    class Foo(BaseModel):
  File "/usr/local/lib/python3.7/site-packages/pydantic/_internal/_model_construction.py", line 177, in __new__
    types_namespace=types_namespace,
  File "/usr/local/lib/python3.7/site-packages/pydantic/_internal/_model_construction.py", line 420, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/usr/local/lib/python3.7/site-packages/pydantic/main.py", line 533, in __get_pydantic_core_schema__
    return __handler(__source)
  File "/usr/local/lib/python3.7/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/usr/local/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 265, in generate_schema
    obj, from_dunder_get_core_schema=from_dunder_get_core_schema, from_prepare_args=from_prepare_args
  File "/usr/local/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 277, in _generate_schema_for_type
    schema = self._generate_schema_from_prepare_annotations(obj)
  File "/usr/local/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 383, in _generate_schema_from_prepare_annotations
    new_obj, new_annotations = self._prepare_annotations(obj, [])
  File "/usr/local/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 1210, in _prepare_annotations
    res = self._get_prepare_pydantic_annotations_for_known_type(source_type, annotations)
  File "/usr/local/lib/python3.7/site-packages/pydantic/_internal/_generate_schema.py", line 1186, in _get_prepare_pydantic_annotations_for_known_type
    from ._std_types_schema import PREPARE_METHODS
  File "/usr/local/lib/python3.7/site-packages/pydantic/_internal/_std_types_schema.py", line 608, in <module>
    typing.OrderedDict: collections.OrderedDict,
AttributeError: module 'typing' has no attribute 'OrderedDict'
```

Tested minimal reproducible example with the following dockerfile:

```yml
FROM python:3.7.1

copy t.py .

run pip install --upgrade pip && \
    pip install "pydantic>=2.0"

cmd python t.py
```

I have tested the same example with `pydantic==1.10.10` and everything works as expected. It also works with a newer version of python 3.7 (tested with 3.7.17 & 3.7.2)

### Example Code

```Python
from pydantic import BaseModel
import pydantic.version


class Foo(BaseModel):
    x:  int
    y: float

if __name__ == "__main__":
    print(pydantic.version.version_info())
    print(Foo(x=5, y=1.1))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: /usr/local/lib/python3.7/site-packages/pydantic
               python version: 3.7.1 (default, Nov 16 2018, 22:26:09)  [GCC 6.3.0 20170516]
                     platform: Linux-5.15.0-72-generic-x86_64-with-debian-9.6
     optional deps. installed: ['typing-extensions']
3.7.1 (default, Nov 16 2018, 22:26:09) 
[GCC 6.3.0 20170516]
```

Selected Assignee: @dmontagu

**Comment by Kludex** [comment]
<img width="799" alt="Screenshot 2023-07-04 at 17 22 37" src="https://github.com/pydantic/pydantic/assets/7353520/01d12dfc-df01-4046-accc-37093128a905">

https://docs.python.org/3/library/typing.html#typing.OrderedDict

Interesting...
