### ISSUE TITLE
dataclasses lose annotation if Field used in inherited class

### ISSUE THREAD

**Issue by mwalsh161** [pydantic/pydantic#8670]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

pydantic 2.6 (confirmed this works in 2.5).

```
Traceback (most recent call last):
  File "pydantic2.6.py", line 9, in <module>
    class B(A):
  File ".../pydantic/dataclasses.py", line 218, in create_dataclass
    cls = dataclasses.dataclass(  # type: ignore[call-overload]
  File ".../dataclasses.py", line 1019, in dataclass
    return wrap(cls)
  File ".../dataclasses.py", line 1011, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File ".../dataclasses.py", line 885, in _process_class
    raise TypeError(f'{name!r} is a field but has no type annotation')
TypeError: 'a' is a field but has no type annotation
```

### Example Code

```Python
from pydantic import dataclasses

class A:
    a: int = dataclasses.Field()

@dataclasses.dataclass()
class B(A):
    ...
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=false
                 install path: .../lib/python3.8/site-packages/pydantic
               python version: 3.8.18 | packaged by conda-forge | (default, Dec 23 2023, 17:23:49)  [Clang 15.0.7 ]
                     platform: macOS-10.16-x86_64-i386-64bit
             related packages: typing_extensions-4.9.0 mypy-1.8.0 fastapi-0.104.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@mwalsh161,

Thanks for reporting this. We'll come up with a fix and hopefully get a patch release out tomorrow!

**Comment by hramezani** [comment]
The issue has been introduced in https://github.com/pydantic/pydantic/commit/2e459bb563dbc296c2bcffbfd1a3caf21241b8e0

**Comment by sydney-runkle** [comment]
@hramezani yep, thanks. I'll open a PR early tomorrow morning.

**Comment by mwalsh161** [comment]
Thanks for the quick turnaround!

**Comment by sydney-runkle** [comment]
@mwalsh161,

What's the use case here for having a class `A` with a `pydantic.dataclasses.Field()` default, when `A` itself isn't decorated with `pydantic.dataclasses.dataclass`?

**Comment by alexmojaki** [comment]
In the stdlib dataclasses source in 3.8, it says:

```python
    for b in cls.__mro__[-1:0:-1]:
        # Only process classes that have been processed by our
        # decorator.  That is, they have a _FIELDS attribute.
        base_fields = getattr(b, _FIELDS, None)
```

Indeed, fields in undecorated base classes are ignored:

```python
import dataclasses


# Uncomment to fix error
# @dataclasses.dataclass()
class A:
    a: int = dataclasses.field()


@dataclasses.dataclass()
class B(A):
    b: str


# TypeError: __init__() got an unexpected keyword argument 'a'
print(B(a=1, b='c'))
```

so maybe pydantic should be imitating that standard?

**Comment by mwalsh161** [comment]
Excellent point - that was a transcription error on my part (our actual use-case wraps both). That case will yield the same error (just reconfirmed on the test script as well).

**Comment by sydney-runkle** [comment]
@mwalsh161,

I've merged a PR with a fix for this issue (in the case of the decorated base class), and we'll include this in the 2.6.1 release shortly 👍
