### ISSUE TITLE
dataclass decorator: unexpected keyword argument using mypy

### ISSUE THREAD

**Issue by BayerSe** [pydantic/pydantic#3647]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/bay2rng/PycharmProjects/semisched/packages/scheduler/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Nov 16 2021, 03:08:02)  [GCC 9.3.0]
                     platform: Linux-5.4.0-90-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']

```

While translating some models implemented using Python's standard dataclass decorator into Pydantic dataclasses, `mypy 0.931` started complaining about unexpected keyword arguments

```py
from dataclasses import dataclass
from pydantic.dataclasses import dataclass as pd_dataclass


@dataclass
class ModelA:
    parameter: int


@pd_dataclass
class ModelB:
    parameter: int


a = ModelA(parameter=1)
b = ModelB(parameter=1)

```

Output of `mypy test.py`

```shell
test.py:16: error: Unexpected keyword argument "parameter" for "ModelB"
```

**Comment by pecigonzalo** [comment]
It seems the return type has some problem, and likely affecting VSCode auto-completion as well which I believe was meant to be fixed in https://github.com/samuelcolvin/pydantic/pull/2721.

If you hover "b" in this example, you will see its type is detected as `(variable) b: Dataclass`.

**Comment by ajkaijanaho** [comment]
The dataclass decorator is annotated as returning a Dataclass object, which defines the Pydantic dataclass additions, losing any information about the original class that is being decorated.  The dataclass transformation defined in #2721 is only applied to ModelMetaclass, which is not the metaclass of dataclasses.

I know of no way to annotate correctly a decorator that modifies a class's methods and fields. You either do what Pydantic does or you annotate like your decorator does not change the class.

**Comment by adriangb** [comment]
This works on both v1.10.X and v2 without issues even with `mypy --strict`, so it seems like it's been resolved.
