### ISSUE TITLE
mypy doesn't work with field type AnyHttpUrl

### ISSUE THREAD

**Issue by decastromonteiro** [pydantic/pydantic#3143]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/***/.cache/pypoetry/virtualenvs/caishen-user-api-3c-BCzZJ-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Aug  8 2021, 10:09:11)  [GCC 9.3.0]
                     platform: Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

```py
from pydantic import AnyHttpUrl, BaseSettings

class Settings(BaseSettings):
    CORS_ORIGINS: List[AnyHttpUrl] = ["http://www.example.com"]
...
```
While running pre-commit with mypy, I get the following error:

```py
api/settings.py:44: error: List item 0 has incompatible type "str"; expected "AnyHttpUrl"
```

Just for reference, I'm using mypy 0.910 with the following config under pyproject.toml

```toml
[tool.mypy]
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
strict_optional = false
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]
disallow_untyped_defs = true
follow_imports = "silent"
```
I've also tried using `mypy.ini`, just to guarantee that it was not a parsing error from pyproject.toml, however the result is the same, so I think something is missing for this type validation on the mypy plugin.

**Comment by phillipuniverse** [comment]
@decastromonteiro does it work if you do a default with `Field`?

```python
class Test2(p.BaseModel):
    CORS_ORIGINS: List[AnyHttpUrl] = p.Field(["http://www.example.com"])


print(Test2())  # output: ['http://www.example.com']'
print(Test2(CORS_ORIGINS=["notaurl"]))  # raises ValidationError`
```

**Comment by peterjkirby** [comment]
@phillipuniverse I am having the same issue. Using `Field` as you recommended fixes the issue for me.

**Comment by nameer** [comment]
I have faced this issue before. I had to use the `parse_obj_as` method:

```py
class Test2(p.BaseModel):
    CORS_ORIGINS: List[AnyHttpUrl] = [p.tools.parse_obj_as(AnyHttpUrl, "http://www.example.com")])
```

Reference: https://github.com/samuelcolvin/pydantic/issues/1106

**Comment by phillipuniverse** [comment]
My method above no longer works with Pydantic 1.10. As @nameer mentioned though, `parse_obj_as` works like a charm!

**Comment by yarikoptic** [comment]
is there hope to get this issue addressed somehow without resorting to `parse_obj_as` tricks?

**Comment by samuelcolvin** [comment]
Have it tried `validate_all`?

https://pydantic-docs.helpmanual.io/usage/model_config/

**Comment by adamsuskin** [comment]
@samuelcolvin that is great! I'm very curious out of interest: why would `True` not be the default setting? Is there a particular reason?

**Comment by samuelcolvin** [comment]
You set the default so it generally doesn't make sense to validate it. It only really matters to vision types like urls which can't be instantiated trivially.

**Comment by dmontagu** [comment]
I think mypy is doing the right thing here, as it's generally correct to "prepare" the value into the correct type up front in python code (considering `Url` is a different class than `str`).

Also, relying on `validate_default` will add conversion overhead each time you instantiate the model, which can be eliminated by something like [@nameer's suggestion above](https://github.com/pydantic/pydantic/issues/3143#issuecomment-1139527466). 

Because I think the conversation in this issue has now addressed why we do things this way, and how to work around it, I'm going to close this issue, but please comment if you feel the issue has not been adequately addressed and we can reconsider how to best address this.
