### ISSUE TITLE
ImportError: cannot import name 'BaseSettings' from 'pydantic_settings' on docker container after migration to V2

### ISSUE THREAD

**Issue by rashidasgari** [pydantic/pydantic#8172]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm starting to have import errors after migration. I get: `ImportError: cannot import name 'BaseSettings' from 'pydantic_settings' (/usr/local/lib/python3.8/site-packages/pydantic_settings/__init__.py)` I have done `pip install pydantic pydantic-settings` and already importing BaseSettings from pydantic_settings.

The same works fine on local machine.

### Python, Pydantic & OS Version

```Text
python 3.9 - not pinning pydantic version.
```

**Comment by hramezani** [comment]
probably `pydantic-settings` is not installed in your environment. run `pip list` to see the installed package in your machine.

Nothing to help here. 

I close this issue for now. please open an issue related to to `pydantic-settings` in [pydantic-settings repo](https://github.com/pydantic/pydantic-settings).
