### ISSUE TITLE
Definition of an unrelated pydantic class causes code to stop failing

### ISSUE THREAD

**Issue by andrewdodd** [pydantic/pydantic#8156]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When upgrading from pydantic 1.9 to 1.10 see a failure because the `parse_obj` function fails to convert a nested object from a `dict` to a python object. However, this failure does NOT occur if there is a different class defined.

Looking at the release notes for 1.10.0, I suspect it is related to the dataclasses rewrite.

This is an example of code that works for 1.9 (and 2.0):
```python
from typing import List
from dataclasses import dataclass
from pydantic import BaseModel

@dataclass
class Child:
    name: str

@dataclass
class Parent:
    children: List[Child]

class ShimParent(Parent):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for child in self.children:
            assert len(child.name) > 0
            print(f"{child} has long enough name")

class Grandparent(BaseModel):
    parent: ShimParent

if __name__ == "__main__":
    payload = {"parent": { "children": [{"name": "child"}] } }
    gp = Grandparent.parse_obj(payload)
    print(gp)
    print("child name is " + gp.parent.children[0].name)
```

Here is an example of me installing various versions of pydantic and then executing the test file:
```
(venv) ➜  pydanticbug pip3 install pydantic==1.9 -q
(venv) ➜  pydanticbug python test.py
parent=_Pydantic_ShimParent_140546976972720(children=[_Pydantic_Child_140546976948272(name='child')])
child name is child
(venv) ➜  pydanticbug pip3 install pydantic==2.0 -q
(venv) ➜  pydanticbug python test.py
...REMOVED WARNING....
parent=ShimParent(children=[Child(name='child')])
child name is child
(venv) ➜  pydanticbug pip3 install pydantic==1.10 -q
(venv) ➜  pydanticbug python test.py
Traceback (most recent call last):
  File "/Users/andydodd/dev/pydanticbug/test.py", line 26, in <module>
    gp = (Grandparent.parse_obj(payload))
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 340, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1148, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 318, in pydantic.class_validators._generic_validator_basic.lambda13
  File "pydantic/dataclasses.py", line 337, in pydantic.dataclasses._validate_dataclass

  File "pydantic/dataclasses.py", line 344, in pydantic.dataclasses._validate_dataclass
    def _tuple_str(obj_name, fields):
  File "pydantic/dataclasses.py", line 297, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
    'frozen',
  File "pydantic/dataclasses.py", line 264, in pydantic.dataclasses._add_pydantic_validation_attributes.handle_extra_init
    f'default_factory={self.default_factory!r},'
  File "/Users/andydodd/dev/pydanticbug/test.py", line 18, in __init__
    assert len(child.name) > 0
AttributeError: 'dict' object has no attribute 'name'
```

However, this example defines the `UnrelatedClass` which is just defined, and it not used anywhere:

```python
from typing import List
from dataclasses import dataclass
from pydantic import BaseModel

@dataclass
class Child:
    name: str

@dataclass
class Parent:
    children: List[Child]

class ShimParent(Parent):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for child in self.children:
            assert len(child.name) > 0
            print(f"{child} has long enough name")

class Grandparent(BaseModel):
    parent: ShimParent


# If the class below here is defined, then the code works in Pydantic 1.10.
class UnrelatedClass(BaseModel):
    items: List[Parent]      # NB: This is NOT the ShimParent, it is the Parent type

if __name__ == "__main__":
    payload = {"parent": { "children": [{"name": "child"}] } }
    gp = Grandparent.parse_obj(payload)
    print(gp)
    print("child name is " + gp.parent.children[0].name)
```

The file now behaves as expected:
```
(venv) ➜  pydanticbug python test.py
Child(name='child') has long enough name
parent=ShimParent(children=[Child(name='child')])
child name is child
```

Questions:
 - I notice that the 1.10 version is the only version that triggers the `print()` that is inside the `ShimParent.__init__` method.  Is this correct?
 - It seems that the conversion done by `parse_obj` depends on the `UnrelatedClass` being defined. Why? Is this definition updating the `Parent` dataclass somehow?

### Example Code

_See above_

### Python, Pydantic & OS Version

```Text
(venv) ➜  pydanticbug python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.10.0
            pydantic compiled: True
                 install path: /...REDACTED.../pydanticbug/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Aug 11 2023, 19:44:50)  [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-13.5.2-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @andrewdodd,

Thanks for reporting this. This does seem like a bug in 1.10. We're prioritizing fixes for v2.5+ at this point, so this isn't a high priority issue.

That being said, it sounds like you've done some digging and found some promising leads as far as the source of the issue goes. Feel free to open a PR with a fix and we can add that to the next v1 patch release 👍, though a better recommendation would be to just use V2 as it's fixed there 😄.

**Comment by andrewdodd** [comment]
Thanks @sydney-runkle ,

Sure, if I can find the time I'll see if I can cut a PR. 

Do you have any hints as to where I should start looking? In particular, should I be figuring out what is happening in the `parse_obj` through to contructor path, and/or why defining a class seems to change the behaviour (or both)?

Additionally, any tips on how to get `pdb` to debug with the installed pydantic package? When I try to step into `parse_obj` I just see a few stops about `string.__init__` and then the function returns...i.e. no stepping in at all.

**Comment by sydney-runkle** [comment]
@andrewdodd,

Good questions. Sounds like you looked into a potential source as the dataclasses rewrite - maybe best to start there. Otherwise, I think looking at why defining a class seems to change the behavior would be best.

We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. Feel free to continue working on this, but for now we're going to leave it as closed for organizational purposes.
