### ISSUE TITLE
AttributeError model.__pydantic_private__.__setitem__

### ISSUE THREAD

**Issue by goudakrishna** [pydantic/pydantic#11646]
### Initial Checks

- [x] I confirm that I'm using Pydantic V2

### Description

In latest version of 2.11.0, getting attribute error.

File "/opt/venv/lib/python3.11/site-packages/pydantic/main.py", line 105, in <lambda>
    'private': lambda model, name, val: model.__pydantic_private__.__setitem__(name, val),  # pyright: ignore[reportOptionalMemberAccess]
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__setitem__'. Did you mean: '__setattr__'?

### Example Code

```Python

```

### Python, Pydantic & OS Version

```Text
python3.11
```

**Comment by Viicos** [comment]
Please provide a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) of your issue, with sample data if available.

**Comment by justin-jeffery-ipf** [comment]
I am also now having this issue since updating to 2.11.  I am not sure how to debug it at all.


`https://gitlab.com/ip-fabric/integrations/python-ipfabric/-/blob/rel-7.2/tests/unittests/client/test_client.py?ref_type=heads#L42`
Branch `rel-7.2`

`poetry run pytest tests/unittests/client/test_client.py::TestIPFClient::test_ipf`


```
============================= test session starts =============================
collecting ... collected 1 item

unittests\client\test_client.py::TestIPFClient::test_ipf 

========================= 1 error in 69.48s (0:01:09) =========================
ERROR           [100%]
test setup failed
module_mocker = <pytest_mock.plugin.MockerFixture object at 0x000001D1E2ABBB30>
loaded_snap = {'creatorUsername': None, 'deviceAddedCount': 0, 'deviceRemovedCount': 0, 'disabled_graph_cache': False, ...}

    @pytest.fixture(scope="module")
    def ipf(module_mocker: MockerFixture, loaded_snap) -> IPFClient:
        module_mocker.patch.object(IPFabricAPI, "model_post_init")
        module_mocker.patch.object(Intent, "model_post_init")
        module_mocker.patch.object(Snapshots, "model_post_init", return_value=None)
        ipf = IPFClient()
        ipf._client = module_mocker.MagicMock()
        ipf.base_url = httpx.URL("")
        ipf.api_version = API_VERSION
        ipf._os_version = VERSION
        ipf._oas = OAS(client=ipf, local_oas=True)
        ipf._user = User(username="test")
        ipf._snapshots = Snapshots(client=ipf)
        loaded = Snapshot(client=ipf, **loaded_snap)
>       ipf._snapshots._snapshots = OrderedDict(
            [
                ("$last", loaded),
                (loaded_snap["id"], loaded),
            ]
        )

unittests\client\test_client.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\.venv\Lib\site-packages\pydantic\main.py:991: in __setattr__
    setattr_handler(self, name, value)  # call here to not memo on possibly unknown fields
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

model = Snapshots(client=IPFClient(base_url='')), name = '_snapshots'
val = OrderedDict({'$last': Snapshot(client=IPFClient(base_url=''), snapshot_id='936509a3-780b-4eec-b608-d6f41df537ad', name...460, unloaded_size=0, disabled_graph_cache=False, disabled_historical_data=False, disabled_intent_verification=False)})

>       'private': lambda model, name, val: model.__pydantic_private__.__setitem__(name, val),  # pyright: ignore[reportOptionalMemberAccess]
        'cached_property': lambda model, name, val: model.__dict__.__setitem__(name, val),
        'extra_known': lambda model, name, val: _object_setattr(model, name, val),
    }
E   AttributeError: 'NoneType' object has no attribute '__setitem__'. Did you mean: '__setattr__'?

..\.venv\Lib\site-packages\pydantic\main.py:105: AttributeError

```

**Comment by Viicos** [comment]
Thanks @justin-jeffery-ipf, this will be fixed in https://github.com/pydantic/pydantic/pull/11666.

@goudakrishna, the issue may happen on your end for the same reasons: you can check if you are overwriting `model_post_init()` in unusual ways (e.g. by mocking, as in https://gitlab.com/ip-fabric/integrations/python-ipfabric/-/blob/rel-7.2/tests/unittests/client/test_client.py?ref_type=heads#L17-22).
