### PR TITLE
Typing extensions min version

### LINKED ISSUE #4885: Pydantic 1.10.3 incompatible with typing-extensions 4.1.1
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

- Installed latest pydantic and typing-extensions 4.1.1
- Code crashes on `import pydantic`

I suspect we just need to bump the min version requirement or fix a cross-version incompatibility, since it works with typing-extensions 4.4.0.

### Example Code

```Python
# Set up a clean venv
# pip install pydantic==1.10.3 typing-extensions==4.1.1

>>> import pydantic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 46, in init pydantic.dataclasses
    # | None    | Attribute is set to None.               |
  File "pydantic/main.py", line 121, in init pydantic.main
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'
```

### Python, Pydantic & OS Version

```Text
Crashes so I can't run that

Tested with python 3.7.9
```

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

### PR DESCRIPTION
**Pull request by samuelcolvin**
fix #4885.

I've checked the [changelog](https://github.com/python/typing_extensions/blob/main/CHANGELOG.md) and tried this locally and everything seems to run fine.

### CODE REVIEW

**Review by PrettyWood — APPROVED** [review]

**Comment by albertvillanova** [comment]
Thanks for the fix.

Are you planning to make a patch release `1.10.4`?

I think this fix should be ported to `pyproject.toml` on the `main` branch as well...

**Review by hramezani — APPROVED** [review]
:+1:

**Comment by samuelcolvin** [comment]
> Are you planning to make a patch release `1.10.4`?

See discussion on #4885.

> I think this fix should be ported to `pyproject.toml` on the `main` branch as well...

I'll push directly to `main` now.
