### ISSUE TITLE
conlist parameters min and max items raises parameter does not exist error

### ISSUE THREAD

**Issue by WalkerJ92** [pydantic/pydantic#7597]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

A simple use of the conlist constraint within pydantic V2 gives an error of "TypeError: conlist() got an unexpected keyword argument 'min_items'". 
This was working in the previous version (1.10).

### Example Code

```Python
from pydantic import conlist

test_list: conlist(float, min_items=2, max_items=4)
```

### Python, Pydantic & OS Version

```Text
Pydantic 2.3.0 version in windows 10, python 3.
```

**Comment by sydney-runkle** [comment]
Hi @WalkerJ92,

Looks like you've got the param names a bit off. This works:

```py
from pydantic import conlist

test_list: conlist(float, min_length=2, max_length=4)
```

See the [API docs here](https://docs.pydantic.dev/2.4/api/types/#pydantic.types.conlist).

**Comment by WalkerJ92** [comment]
Thanks. Was reading the documentation for v1 apparently. https://docs.pydantic.dev/1.10/usage/types/#constrained-types

**Comment by sydney-runkle** [comment]
@WalkerJ92 Sure thing! Happens to the best of us!
