### ISSUE TITLE
`mypy` type-checking issues affecting a `Field`'s `default` value or `default_factory` after upgrade to 2.10

### ISSUE THREAD

**Issue by ruslan-roboto** [pydantic/pydantic#10950]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

After upgrading to Pydantic 2.10.0, we started getting certain type-checking issues with `mypy`. The majority of them are already tracked as issues, and some were resolved in Pydantic 2.10.1. However, there are a few that still persist even on 2.10.1, and I don't think they're already tracked:

* a field of type `Foo(str, Enum)` cannot be given a default value like `Field(default="some-str")` because of incompatible types (`str` vs. `Foo`).
* a field of type `SecretStr` cannot be given a default `str` value like `Field(default="NOT_SET")`, again because of incompatible types
* optional list/dict fields explicitly marked as e.g.`Optional[list[str]]` cannot be given a `Field` definition with a `default_factory=list` or `default_factory=dict`.

Maybe some of those changes are intentional, but I wanted to raise them since existing code with the above idioms used to type-check before 2.10.x.

Whether or not you restore the pre-2.10 type-checking behavior, what would be the preferred ways to provide default values/factories for such fields? Please also see the example code below.

### Example Code

```Python
import pydantic
import pydantic_settings
from typing import Optional, Any

class Color(str, enum.Enum):
    Red = "red"
    Blue = "blue"
    Green = "green"

class AppConfig(pydantic_settings.BaseSettings):
    color: Color = pydantic.Field(default="NOT_SET", alias="ENV_COLOR")
    secret_key: SecretStr = pydantic.Field(default="NOT_SET", alias="ENV_SECRET_KEY")

class AppRequest(pydantic.BaseModel):
    names: Optional[list[str]] = pydantic.Field(default_factory=list)
    metadata: Optional[dict[str, Any]] = pydantic.Field(default_factory=dict)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.1
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: <redacted>
               python version: 3.10.15+ (heads/3.10:0c5fc27, Sep 23 2024, 11:19:43) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.7-arm64-arm-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by ruslan-roboto** [comment]
Additional related packages:
* `pydantic_settings-2.6.1`
* `mypy-1.13.0`

**Comment by jamesbraza** [comment]
I am facing a similar issue where the below is fine with `pydantic<2.10`, but with `pydantic==2.10.1` `mypy` errors:

```python
import contextvars

from pydantic import BaseModel, Field

cvar_session_id = contextvars.ContextVar[None]("session_id", default=None)


class Foo(BaseModel):
    session_id: None = Field(default_factory=cvar_session_id.get)
```

`mypy==1.13.0` error:

```none
a.py: note: In class "Foo":
a.py:9:46: error: Argument "default_factory" to "Field" has incompatible type overloaded function; expected "Callable[[], Never] | Callable[[dict[str, Any]], Never]"  [arg-type]
        session_id: None = Field(default_factory=cvar_session_id.get)
                                                 ^~~~~~~~~~~~~~~~~~~
```

**Comment by sydney-runkle** [comment]
Dupe of https://github.com/pydantic/pydantic/issues/10945 perhaps?

**Comment by varnenec** [comment]
@sydney-runkle the `default_factory` examples above produce a different error than "too few arguments" - it's about type mismatch - so I'm not sure if it is a dupe. The `default` examples seem like a separate issue.

**Comment by Viicos** [comment]
This is most likely a limitation in the mypy inference logic. I've raised https://github.com/python/mypy/issues/18191 in the meanwhile. For reference, both pyright and pyre understand these use cases correctly. Until mypy supports it, adding a `type: ignore` seems like the best way forward.

I'll leave this issue open for a while, as we may try going with a different workaround if this raises too many issues.

**Comment by vitalii-diachkov-sumup** [comment]
I am facing the same issue with slightly the following example:

```python
from pydantic import BaseModle, Field

class MyModel(BaseModel):
    prop: dict[str, Any] | None = Field(default_factory=dict)
```

This raises the following `mypy` error:

```
Argument "default_factory" to "Field" has incompatible type "type[dict[Any, Any]]"; expected "Callable[[], Never] | Callable[[dict[str, Any]], Never]" [arg-type]
```

- Pydantic: `v2.10.2`
- Mypy: `v1.13.0`

**Comment by Pwuts** [comment]
Related:
- #11052

**Comment by mhdzumair** [comment]
+1 :(

**Comment by sigma67** [comment]
> Dupe of #10945 perhaps?

Not a duplicate, the issue is still around with the latest patch

**Comment by fritz-trawa** [comment]
I still get the issue with 2.11 

```
Argument "default_factory" to "Field" has incompatible type "type[dict[Any, Any]]"; expected "Callable[[], Never] | Callable[[dict[str, Any]], Never]" [arg-type]
```

but only for `args: Optional[dict[str, Any]] = Field(default_factory=dict)` not `args: dict[str, Any] = Field(default_factory=dict)`

**Comment by Viicos** [comment]
Seems like since mypy 1.16.0, the issue got fixed. There are still some closely related issues (tracked in https://github.com/python/mypy/issues/18191). I'm going to close this one for now as the reported use case now works.
