### ISSUE TITLE
mypy error when using `_env_file` in BaseSettings sub-class

### ISSUE THREAD

**Issue by duckontheweb** [pydantic/pydantic#3072]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/jduckworth/.pyenv/versions/3.8.9/envs/mlhub-backend-dev/lib/python3.8/site-packages/pydantic
               python version: 3.8.9 (default, Apr 23 2021, 14:38:08)  [Clang 12.0.0 (clang-1200.0.32.28)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

Running `mypy --show-error-codes ./pydantic_mypy_error.py` with the files shown below gives the following error:

```
pydantic_mypy_error.py:9: error: Unexpected keyword argument "_env_file" for "EnvFileBaseSettings"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

### `mypy.ini`

```
[mypy]
plugins = pydantic.mypy
```

### `pydantic_mypy_error.py`

```python

from pydantic import BaseSettings


class EnvFileBaseSettings(BaseSettings):
    my_var: str


if __name__ == "__main__":
    _ = EnvFileBaseSettings(_env_file=".test.env")
```

### `.test.env`
```
# .test.env
MY_VAR=thing
```

Selected Assignee: @davidhewitt

**Comment by bameda** [comment]
I have the same error.

**Comment by laryssonalves** [comment]
I'm facing the same problem, it started happening when I added the `pydantic.mypy` plugin to the mypy.ini file. This is an old ticket, Any nobody knows how to fix it?

**Comment by paul-papacz** [comment]
I can confirm this with:
* Pydantic version `1.10.5`
* mypy version `1.0.1`
* with
  ```
  [tool.mypy]
  plugins = [ "pydantic.mypy" ]
  ```
  in `pyproject.toml`

**Comment by dmontagu** [comment]
If someone wants to work on this, this is the part of the mypy plugin that is responsible for setting the `__init__` signature of a BaseModel:

https://github.com/pydantic/pydantic/blob/6267ae3538cf7237ff6769174b4c340415e0f444/pydantic/mypy.py#L484-L503

(Likely you'd want to augment the call to `get_field_arguments` with something that grabs the non-`**kwargs` arguments off the base signature.)

I think it would be an improvement if the mypy plugin introspected the initializer function's signature and retained all explicitly-added keyword arguments, which I think would solve the issue for BaseSettings _and_ other models where the `__init__` method gets overridden with extra arguments.

-----

It would also be possible (and perhaps easier?) to do something BaseSettings-specific by creating a subclass of `PydanticModelTransformer` (likely calling it something like `PydanticSettingsTransformer`), override the `add_initializer` method as appropriate, and then add a handler for `BaseSettings` as appropriate here:

https://github.com/pydantic/pydantic/blob/6267ae3538cf7237ff6769174b4c340415e0f444/pydantic/mypy.py#L114-L115

That said, I think for various reasons it would be preferable to make the change described above since that would address this shortcoming of the plugin for any subclass of `BaseModel`, not just `BaseSettings`.

**Comment by dmontagu** [comment]
This is due to the use of `@dataclass_transform` being respected in mypy 1.1.1.

I think this is unlikely to get fixed in pydantic v1 unless fixing it in v2 can be trivially backported. (Note: we still need to implement pydantic_settings for v2.) I would recommend just using a `# type: ignore[call-arg]` for this until then.

That said, if someone wants to take a stab at fixing this in the (v1) mypy plugin, I'd be happy to point you in the right direction and review/merge a PR fixing it.

**Comment by hramezani** [comment]
Thanks @stijndegooijer for letting us know.

**Comment by jc-rosier** [comment]
Hello, even with python 3.11, pydantic-settings 2.0.2 and mypy 1.4.1 I got the error:

`error: Unexpected keyword argument "_env_file" for "Settings"  [call-arg]`
Found 1 error in 1 file (checked 1 source file)

```python
from pydantic_settings import BaseSettings

class Settings(BaseSettings)
    pass

Settings(_env_file="")
```

Also using plugin = ["pydantic.mypy"] in pyproject.toml

Thanks for your help

**Comment by johnthagen** [comment]
I agree with @jc-rosier I still get these errors. This issue should be reopened.

```
mypy                      1.4.1
pydantic                  2.0.2
pydantic_core             2.1.2
pydantic-settings         2.0.1
```


```toml
[tool.mypy]
ignore_missing_imports = true
strict = true
disallow_untyped_decorators = false

plugins = [
    "pydantic.mypy",
]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
```

**Comment by stijndegooijer** [comment]
Using `SettingsConfigDict` I am having no issues. You can try using that syntax.

I believe the syntax you're using is officially documented as well, though passing arguments starting with underscores is a big hint that it might not be the real intended way to do things.

```python
from pydantic_settings import BaseSettings
from pydantic_settings import SettingsConfigDict

class Settings(BaseSettings)
    
    model_config = SettingsConfigDict(env_file=".env")

Settings()
```

**Comment by jc-rosier** [comment]
We are not talking about the same thing here, please stop confusing the thread.

https://docs.pydantic.dev/latest/usage/pydantic_settings/#dotenv-env-support

As in the official documentation of pydantic settings, I want to use the _env_file keyword argument to override the env file location at runtime.

> Instantiating the BaseSettings derived class with the _env_file keyword argument (and the _env_file_encoding if needed):

```python
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file='.env', env_file_encoding='utf-8')


settings = Settings(_env_file='prod.env', _env_file_encoding='utf-8')
```

`error: Unexpected keyword argument "_env_file" for "Settings"  [call-arg]`

**Comment by johnthagen** [comment]
@jc-rosier Is correct. The documented way to control the Env file at runtime (`_env_file`) still produces false positive type checking errors. 

@hramezani Could you please re-open this issue? Thanks.

**Comment by hramezani** [comment]
Fixed in https://github.com/pydantic/pydantic/commit/5660c8c1c8777d57ffecd805ff80da182a4a43e1

**Comment by glemeur** [comment]
Hello, 

Thanks for working on this issue previously! 

After updating mypy to 1.5.1 (from 0.991) I started to experience the same issue, even using pydantic.mypy plugin configured in pyproject.toml as in the [doc](https://docs.pydantic.dev/latest/integrations/mypy/#configuring-the-plugin).

Versions (using Poetry):
```
mypy==1.5.1
pydantic==2.4.2
pydantic-settings==2.0.3
pydantic_core==2.10.1
```

Using JC-rosier example just above I have two errors:
```
error: Unexpected keyword argument "_env_file" for "Settings"  [call-arg]
error: Unexpected keyword argument "_env_file_encoding" for "Settings"  [call-arg]
```

Your help would be highly appreciated, thanks.

**Comment by facundopadilla** [comment]
It works fine for me:

First file:


```python
# src/settings/base.py
from dotenv import find_dotenv
from pydantic_settings import BaseSettings
from pydantic_settings import SettingsConfigDict

class BaseSettingsProject(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=find_dotenv(".env.local"),
    )
```

Second file:
```python
# src/settings/auth.py

from pydantic import Field
from pydantic import SecretStr

from src.settings.base import BaseSettingsProject

class _AuthSettings(BaseSettingsProject):
    SECRET_KEY: SecretStr = Field(..., description="Authentication secret key")


AuthSettings = _AuthSettings(_env_prefix="AUTH_")

```
