### ISSUE TITLE
AwareDatetime not working with python 3.14

### ISSUE THREAD

**Issue by jfra1397** [pydantic/pydantic#12564]
### Initial Checks

- [x] I confirm that I'm using Pydantic V2

### Description

using `AwareDatetime` object with Pyhton 3.14 seems to cause problems:
```
$ uv run test.py
Traceback (most recent call last):
  File "/.cache/uv/environments-v2/test-env/lib/python3.14/site-packages/pydantic/_internal/_typing_extra.py", line 455, in eval_type_backport
    return _eval_type_backport(value, globalns, localns, type_params)
  File "/.cache/uv/environments-v2/test-env/lib/python3.14/site-packages/pydantic/_internal/_typing_extra.py", line 492, in _eval_type_backport
    return _eval_type(value, globalns, localns, type_params)
  File "/.cache/uv/environments-v2/test-env/lib/python3.14/site-packages/pydantic/_internal/_typing_extra.py", line 524, in _eval_type
    evaluated = typing._eval_type(  # type: ignore
        value,
    ...<9 lines>...
        prefer_fwd_module=True,
    )
TypeError: _eval_type() got an unexpected keyword argument 'prefer_fwd_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    class Foo(BaseModel):
        timestamp: AwareDatetime
  File "/.cache/uv/environments-v2/test-env/lib/python3.14/site-packages/pydantic/_internal/_model_construction.py", line 242, in __new__
    set_model_fields(cls, config_wrapper=config_wrapper, ns_resolver=ns_resolver)
  File "/.cache/uv/environments-v2/test-env/lib/python3.14/site-packages/pydantic/_internal/_model_construction.py", line 566, in set_model_fields
    fields, class_vars = collect_model_fields(cls, config_wrapper, ns_resolver, typevars_map=typevars_map)
  File "/.cache/uv/environments-v2/test-env/lib/python3.14/site-packages/pydantic/_internal/_fields.py", line 256, in collect_model_fields
    type_hints = _typing_extra.get_model_type_hints(cls, ns_resolver=ns_resolver)
  File "/.cache/uv/environments-v2/test-env/lib/python3.14/site-packages/pydantic/_internal/_typing_extra.py", line 350, in get_model_type_hints
    hints[name] = try_eval_type(value, globalns, localns)
  File "/.cache/uv/environments-v2/test-env/lib/python3.14/site-packages/pydantic/_internal/_typing_extra.py", line 404, in try_eval_type
    return eval_type_backport(value, globalns, localns), True
  File "/.cache/uv/environments-v2/test-env/lib/python3.14/site-packages/pydantic/_internal/_typing_extra.py", line 462, in eval_type_backport
    assert isinstance(value, typing.ForwardRef)
AssertionError
```

### Example Code

```Python
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "pydantic>=2.12,<3.0",
# ]
# ///

from pydantic import BaseModel, AwareDatetime, __version__


class Foo(BaseModel):
    timestamp: AwareDatetime
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.12.4
        pydantic-core version: 2.41.5
          pydantic-core build: profile=release pgo=false
               python version: 3.14.0rc2 (main, Sep  2 2025, 14:17:48) [Clang 20.1.4 ]
                     platform: macOS-26.1-arm64-arm-64bit-Mach-O
             related packages: typing_extensions-4.15.0
                       commit: unknown
```
