### ISSUE TITLE
_eval_type() got an unexpected keyword argument 'type_params' under Python 3.13 

### ISSUE THREAD

**Issue by Alexey-T** [pydantic/pydantic#10628]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Under Linux under Python 3.13 my user got this error:
```
Traceback (most recent call last):
  File "/home/dwight/.config/cudatext/py/cuda_lsp/__init__.py", line 1, in <module>
    from .lsp import Command
  File "/home/dwight/.config/cudatext/py/cuda_lsp/lsp.py", line 36, in <module>
    from .language import CompletionMan, DiagnosticsMan, Language
  File "/home/dwight/.config/cudatext/py/cuda_lsp/language.py", line 54, in <module>
    from .sansio_lsp_client import client as lsp
  File "/home/dwight/.config/cudatext/py/cuda_lsp/sansio_lsp_client/__init__.py", line 3, in <module>
    from .client import *
  File "/home/dwight/.config/cudatext/py/cuda_lsp/sansio_lsp_client/client.py", line 6, in <module>
    from pydantic import parse_obj_as, ValidationError
  File "/home/dwight/.config/cudatext/py/cuda_lsp/lsp_modules/pydantic/__init__.py", line 7, in <module>
    from pydantic.env_settings import BaseSettings
  File "/home/dwight/.config/cudatext/py/cuda_lsp/lsp_modules/pydantic/env_settings.py", line 23, in <module>
    class BaseSettings(BaseModel):
  File "/home/dwight/.config/cudatext/py/cuda_lsp/lsp_modules/pydantic/main.py", line 178, in __new__
    annotations = resolve_annotations(namespace.get('__annotations__', {}), namespace.get('__module__', None))
  File "/home/dwight/.config/cudatext/py/cuda_lsp/lsp_modules/pydantic/typing.py", line 403, in resolve_annotations
    value = _eval_type(value, base_globals, None, type_params=())
TypeError: _eval_type() got an unexpected keyword argument 'type_params'
```

It worked ok on Py 3.12.

### Python, Pydantic & OS Version

- Pydantic '1.10.17'
- Python 3.13.0a4

### Affected Components

- [x] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
Please upgrade to a non beta version of Python 3.13.
