### ISSUE TITLE
API Breakage: model_rebuild() crashes with TypeError due to mismatched SchemaValidator.new() signature

### ISSUE THREAD

**Issue by wenwen-666** [pydantic/pydantic#12927]
### Initial Checks

- [x] I confirm that I'm using Pydantic V2

### Description

This issue was detected by our testing tool and confirmed after discussion among multiple developers. 
A critical breaking change was introduced in PR #12689 ("Do not re-use prebuilt serializers/validators on rebuilds"), where a new _use_prebuilt keyword parameter was added to the Rust implementation of SchemaValidator.new(), but this parameter was not correctly exposed to the Python runtime. As a result, calls to BaseModel.model_rebuild() and PluggableSchemaValidator immediately raise a TypeError: SchemaValidator.__new__() got an unexpected keyword argument '_use_prebuilt', breaking all existing code that relies on these core APIs. The expected behavior is that model_rebuild() should execute without errors, and SchemaValidator should properly accept the _use_prebuilt parameter at runtime, avoiding such breaking changes to public interfaces.

### Example Code

```Python
from pydantic import BaseModel

# Minimal reproduction example
class SimpleModel(BaseModel):
    name: str
    value: int

# This call directly triggers the crash
SimpleModel.model_rebuild()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.0.dev (git commit from PR #12689)
python version: 3.10.13
platform: Ubuntu 22.04
```

**Comment by Viicos** [comment]
Complete slop, as all your other Github reports.
