### ISSUE TITLE
ImportError: cannot import name 'KeyType' from 'pydantic.utils' 

### ISSUE THREAD

**Issue by atompie** [pydantic/pydantic#6582]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When:

```
from pydantic.utils import deep_update, KeyType
```
I get:

```
ImportError: cannot import name 'KeyType' from 'pydantic.utils' (/root/agent/work/896e56c249cc99e4/.venv/lib/python3.9/site-packages/pydantic/utils.py)
```

It works in v1.0

### Example Code

```Python
from pydantic.utils import deep_update, KeyType
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /home/risto/PycharmProject/pythonProject/errotKasuj/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]
                     platform: Linux-5.4.0-153-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by Viicos** [comment]
In v1 `KeyType = TypeVar('KeyType')`, you can switch your import to `from pydantic.v1.utils import deep_update, KeyType`. Could you provide an example of how your are using `KeyType`? You can define your own `TypeVar` as well, it isn't required to use the same from the `utils` module.

**Comment by atompie** [comment]
@Viicos Sorry for late response. I use it for type hint. 

```python
from pydantic.utils import deep_update, KeyType

    @staticmethod
    def _deep_update(mapping: Dict[KeyType, Any], *updating_mappings: Dict[KeyType, Any]) -> Dict[KeyType, Any]:
        updated_mapping = mapping.copy()
        for updating_mapping in updating_mappings:
            for k, v in updating_mapping.items():
                if k in updated_mapping and isinstance(updated_mapping[k], dict) and isinstance(v, dict):
                    updated_mapping[k] = deep_update(updated_mapping[k], v)
                elif v is not None:
                    updated_mapping[k] = v
        return updated_mapping
```

**Comment by Viicos** [comment]
Then your solution is either:

```python
from pydantic.v1.utils import deep_update, KeyType

    @staticmethod
    def _deep_update(mapping: Dict[KeyType, Any], *updating_mappings: Dict[KeyType, Any]) -> Dict[KeyType, Any]:
        updated_mapping = mapping.copy()
        for updating_mapping in updating_mappings:
            for k, v in updating_mapping.items():
                if k in updated_mapping and isinstance(updated_mapping[k], dict) and isinstance(v, dict):
                    updated_mapping[k] = deep_update(updated_mapping[k], v)
                elif v is not None:
                    updated_mapping[k] = v
        return updated_mapping
```

or

```python
from typing import TypeVar

from pydantic.v1.utils import deep_update

KeyType = TypeVar("KeyType")

    @staticmethod
    def _deep_update(mapping: Dict[KeyType, Any], *updating_mappings: Dict[KeyType, Any]) -> Dict[KeyType, Any]:
        updated_mapping = mapping.copy()
        for updating_mapping in updating_mappings:
            for k, v in updating_mapping.items():
                if k in updated_mapping and isinstance(updated_mapping[k], dict) and isinstance(v, dict):
                    updated_mapping[k] = deep_update(updated_mapping[k], v)
                elif v is not None:
                    updated_mapping[k] = v
        return updated_mapping
```

**Comment by hramezani** [comment]
Thanks @Viicos for the clear response
