### PR TITLE
Take `populate_by_name` and `validate_by_alias` into account when generating arguments schemas

### LINKED ISSUE #13687: `populate_by_name` (and implicit `validate_by_name` when `validate_by_alias=False`) is ignored by `@validate_call`
### Initial Checks

- [x] I confirm that I'm using Pydantic V2

### Description

Since v2.11, `@validate_call(config=ConfigDict(populate_by_name=True))` no longer allows passing an aliased parameter by its name — the same config on a `BaseModel` works, and the [`populate_by_name` docs](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.populate_by_name) say it is strictly equivalent to `validate_by_name=True, validate_by_alias=True` (deprecated in v3, but still supported). Works on 2.10.6; broken on 2.11.x, 2.12.x, and `main`.

A worse variant: `@validate_call(config=ConfigDict(validate_by_alias=False))` makes the aliased parameter impossible to provide at all (both name and alias raise), even though #11503 made `validate_by_alias=False` implicitly enable `validate_by_name`.

Root cause: `_arguments_schema()`/`_arguments_v3_schema()` embed `validate_by_name=self._config_wrapper.validate_by_name` into the core schema (`_generate_schema.py:2081/2149`), reading the raw config key. The backwards-compatibility patch mapping `populate_by_name` → `validate_by_name` only runs inside `ConfigWrapper.core_config()`, and pydantic-core gives the schema-embedded value precedence over the validator config, so the patched core config is never consulted. Models are unaffected because model-fields schemas don't embed the flag.

I have a fix ready and will open a PR.

### Example Code

```python
from typing import Annotated
from pydantic import Field, validate_call

@validate_call(config=dict(populate_by_name=True))
def f(a: Annotated[int, Field(alias='b')]) -> int:
    return a

f(b=1)  # OK
f(a=1)  # ValidationError: Unexpected keyword argument
```

### Python, Pydantic & OS Version

```text
             pydantic version: 2.14.0b1
        pydantic-core version: 2.48.0
          pydantic-core build: profile=release pgo=false
               python version: 3.11.14 (main, Oct  9 2025, 16:16:55) [Clang 17.0.0 (clang-1700.4.4.1)]
                     platform: macOS-26.5.2-arm64-arm-64bit
             related packages: typing_extensions-4.16.0
                       commit: 2151025
```

(also reproduced on released pydantic 2.11.10 and 2.12.5; not reproducible on 2.10.6)

### PR DESCRIPTION
**Pull request by 2sumtech**
## Change Summary

`ConfigWrapper.core_config()` applies backwards-compatibility patches for the alias configuration settings (`populate_by_name` → `validate_by_name`, and implicit `validate_by_name=True` when `validate_by_alias=False`, per #11503). However, `_arguments_schema()` and `_arguments_v3_schema()` embed `validate_by_name` into the core schema via a direct `ConfigWrapper` attribute access, which bypasses those patches — and the schema-embedded value takes precedence over the core config in pydantic-core. As a result, `@validate_call(config=ConfigDict(populate_by_name=True))` rejects by-name arguments (regression: works on 2.10.6, broken since 2.11), and `validate_by_alias=False` makes aliased parameters impossible to provide at all.

This makes `validate_by_name` a runtime property on `ConfigWrapper` applying the same resolution as `core_config()`, so direct attribute accesses (arguments schema generation, `__signature__` generation) stay consistent with the emitted core config. The property lives in the existing `if not TYPE_CHECKING:` block, keeping the annotation contract with `ConfigDict` intact.

Tests: `test_populate_by_name_still_effective` and `test_validate_by_alias_disabled` in `tests/test_validate_call.py` — both fail without the fix and pass with it. Surrounding suites: `test_validate_call.py` 62 passed; `test_config.py`+`test_model_signature.py`+`test_internal.py`+`test_aliases.py` 255 passed; `test_main.py`+`test_dataclasses.py`+`test_experimental_arguments_schema.py`+`test_deprecated_validate_arguments.py` 549 passed. `ruff check`/`ruff format --check` clean.

## Related issue number

fix #13687

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Documentation reflects the changes where applicable

Disclosure: this fix was developed with the assistance of Claude (Anthropic); I reviewed and tested all changes.

### CODE REVIEW

**Comment by 2sumtech** [comment]
please review
