### ISSUE TITLE
`populate_by_name` (and implicit `validate_by_name` when `validate_by_alias=False`) is ignored by `@validate_call`

### ISSUE THREAD

**Issue by 2sumtech** [pydantic/pydantic#13687]
### Initial Checks

- [x] I confirm that I'm using Pydantic V2

### Description

Since v2.11, `@validate_call(config=ConfigDict(populate_by_name=True))` no longer allows passing an aliased parameter by its name — the same config on a `BaseModel` works, and the [`populate_by_name` docs](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.populate_by_name) say it is strictly equivalent to `validate_by_name=True, validate_by_alias=True` (deprecated in v3, but still supported). Works on 2.10.6; broken on 2.11.x, 2.12.x, and `main`.

A worse variant: `@validate_call(config=ConfigDict(validate_by_alias=False))` makes the aliased parameter impossible to provide at all (both name and alias raise), even though #11503 made `validate_by_alias=False` implicitly enable `validate_by_name`.

Root cause: `_arguments_schema()`/`_arguments_v3_schema()` embed `validate_by_name=self._config_wrapper.validate_by_name` into the core schema (`_generate_schema.py:2081/2149`), reading the raw config key. The backwards-compatibility patch mapping `populate_by_name` → `validate_by_name` only runs inside `ConfigWrapper.core_config()`, and pydantic-core gives the schema-embedded value precedence over the validator config, so the patched core config is never consulted. Models are unaffected because model-fields schemas don't embed the flag.

I have a fix ready and will open a PR.

### Example Code

```python
from typing import Annotated
from pydantic import Field, validate_call

@validate_call(config=dict(populate_by_name=True))
def f(a: Annotated[int, Field(alias='b')]) -> int:
    return a

f(b=1)  # OK
f(a=1)  # ValidationError: Unexpected keyword argument
```

### Python, Pydantic & OS Version

```text
             pydantic version: 2.14.0b1
        pydantic-core version: 2.48.0
          pydantic-core build: profile=release pgo=false
               python version: 3.11.14 (main, Oct  9 2025, 16:16:55) [Clang 17.0.0 (clang-1700.4.4.1)]
                     platform: macOS-26.5.2-arm64-arm-64bit
             related packages: typing_extensions-4.16.0
                       commit: 2151025
```

(also reproduced on released pydantic 2.11.10 and 2.12.5; not reproducible on 2.10.6)

**Comment by 2sumtech** [comment]
The fix is ready in #13688 (closed by the assignment bot) — regression tests fail on main and pass with it, full test_validate_call.py green. Could I be assigned so it can be reopened?
