### ISSUE TITLE
Infinite recursion with a recursive TypeAlias

### ISSUE THREAD

**Issue by aabdagic** [pydantic/pydantic#8346]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Running this code produces infinite recursion:
```
from typing import Mapping, TypeAlias
from pydantic import BaseModel

RecursiveType: TypeAlias = "str | Mapping[str, RecursiveType]"


class Model(BaseModel):
    value: RecursiveType
```

By comparison, this code runs just fine:
```
from typing import Mapping
from pydantic import BaseModel
from typing_extensions import TypeAliasType

RecursiveType = TypeAliasType("RecursiveType", "str | Mapping[str, RecursiveType]")


class Model(BaseModel):
    value: RecursiveType
```

However, mypy really doesn't like this:

```
min_repro.py:8: error: Variable "min_repro.RecursiveType" is not valid as a type  [valid-type]
min_repro.py:8: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
```

fyi, Python 3.12 is also introducing the `type` statement: https://docs.python.org/3/reference/simple_stmts.html#the-type-statement. I didn't test how would this work in Python 3.12 both with and without the `type` keyword.

### Example Code

```Python
from typing import Mapping, TypeAlias

from pydantic import BaseModel

RecursiveType: TypeAlias = "str | Mapping[str, RecursiveType]"


class Model(BaseModel):
    value: RecursiveType
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: <snip>
               python version: 3.10.13 (main, Nov 24 2023, 12:37:35) [GCC 13.2.0]
                     platform: Linux-6.5.6-1rodete4-amd64-x86_64-with-glibc2.37
             related packages: typing_extensions-4.8.0
```

**Comment by adriangb** [comment]
This is expected. We can’t detect the recursion with a regular type alias. Have you tried updating mypy? The latest versions work with TypeAliasType.

**Comment by aabdagic** [comment]
Yup, I'm running mypy 1.7.1.

Looks like it's an open issue, though there may be alignment that it should happen: https://github.com/python/mypy/issues/16614

And possibly an implementation in progress: https://github.com/python/mypy/pull/16644

**Comment by adriangb** [comment]
Try this:

```python
if TYPE_CHECKING:
    Foo = List[Foo]
else:
    Foo = TypeAliasType(…)
