### ISSUE TITLE
Create a model dynamically with create_model() specifying a subset of fields in V2

### ISSUE THREAD

**Issue by tteguayco** [pydantic/pydantic#9573]
### Discussed in https://github.com/pydantic/pydantic/discussions/9449

<div type='discussions-op-text'>

<sup>Originally posted by **tteguayco** May 17, 2024</sup>
We're able to create a new model dynamically using `create_model()` like this:

```python
from pydantic import create_model

base_model = ...
new_model = create_model('MyNewModel', base_model)
```

The problem is that `base_model` may contain certain fields that I don't want them to be included in `new_model`.

Is there any solution to this in Pydantic V2?</div>

**Comment by tteguayco** [comment]
Sorry for the mention, @sydney-runkle.

Do you know if there's a way of doing this? It's a little important for us.

**Comment by sydney-runkle** [comment]
@tteguayco,

Do you want to exclude said fields just for serialization, or during validation as well?

**Comment by tteguayco** [comment]
@sydney-runkle

It should be a new model that doesn't include those fields at all.

**Comment by sydney-runkle** [comment]
Yep, gotcha. This reminds me of https://github.com/pydantic/pydantic/discussions/6699

**Comment by tteguayco** [comment]
Thank you for your answer, @sydney-runkle.

After some back-and-forth attempts, marking the fields as `exclude = True`, makes the new model have them also excluded.

```python
for field_name in list(base_model.model_fields.keys()):
    if  field_name in exclude:
        base_model.model_fields.get(field_name).exclude = True

new_model = create_model('MyNewModel', __base__=base_model)
```

However, an issue I've faced with this approach is that the fields are included if the newly-created model is used to create a second new model:

```python
class MyNewModelTwo(new_model):
    ....
```

I'm really surprised Pydantic doesn't provide a method to exclude fields in an inherited model out of the box, instead of doing of this handcrafting work.

**Comment by tteguayco** [comment]
We can mark the above answer as the solution, at least for my specific problem.

**Comment by sydney-runkle** [comment]
@tteguayco,

We can leave this open - it's a pretty heavily requested feature, so I think it'll be great to leave this open as a feature request. I'll work on an API design. I think this can fit into the scope of v2.9!

**Comment by ShravanSunder** [comment]
So my solution has been

ParentTool.model_fields
create_model(
  "ChildTool",
  __config__=AgentTool.model_config,
  description=(AgentTool.model_fields["description"].annotation, ...),
  tags=(AgentTool.model_fields["tags"].annotation, ...),
)

looks like its working to pick a subset of the parent fields

**Comment by victorventuri** [comment]
I am very new to pydantic so please correct me if anything I say below is wrong. 

I have recently ran into a similar situation as that to @tteguayco and @david-shiko from #2686. 

I haven't tried @ShravanSunder 's solution, but my intuition is that it should work, though it would be a bit annoying if you have a lot of fields in the parent class and only want to exclude a few... it appears you would have to re-list every field you want to include. 

What I tried (and it seems to be working for my case at least) is a combination of responses from @tux-mind and @H-G-11 (from #6699). Basically, you redefine the fields you want to exclude to skip the schema, and delete them post_init. Here's my simple code snippet: 

```
from typing import Any
from pydantic import Field, BaseModel
from pydantic.json_schema import SkipJsonSchema

class Parent(BaseModel):
    a: str = 'a'

class Child(Parent):
    a: SkipJsonSchema[str] = Field('a', exclude=True)
    b: str = 'b'

    def model_post_init(self, __context: Any) -> None:
        del self.model_fields['a']
        delattr(self, 'a')
        return super().model_post_init(__context)

parent = Parent()
print('Parent')
print(parent.model_fields.keys())
print('----------------------------')
child = Child()
print('Child')
print(child.model_fields.keys())
print(child.model_dump())
print(child.model_json_schema())
print(child.a)
```

The outputs of this are:
```
Parent
dict_keys(['a'])
----------------------------
Child
dict_keys(['b'])
{'b': 'b'}
{'properties': {'b': {'default': 'b', 'title': 'B', 'type': 'string'}}, 'title': 'Child', 'type': 'object'}
[...]
AttributeError: 'Child' object has no attribute 'a'
```
(AttributeError being raised because I deleted the attribute from the class during post_init)


As I mentioned, I am very new to pydantic, so there's a good chance some of these things I suggest/implement are not quite right or bad practice. Keeping my fingers crossed that in future versions excluding inherited unwanted field(s) will be more straight-forward.  

Finally, for full disclosure, here is the pydantic version info (installation path deleted for privacy reasons):
```
pydantic version: 2.7.4
pydantic-core version: 2.18.4
pydantic-core build: profile=release pgo=false
install path: /None/of/your/business/pydantic
python version: 3.9.6 (default, Feb  3 2024, 15:58:27)  [Clang 15.0.0 (clang-1500.3.9.4)]
platform: macOS-14.5-arm64-arm-64bit
related packages: typing_extensions-4.12.2
commit: unknown
```

**Comment by k7** [comment]
Finally, I've got it working! Here's my solution. 

However, VSCode doesn't seem to like it anymore; there are no code hints.

Is there a way to resolve this using inheritance?

```
def omit_model_fields(base: type[BaseModel], exclude_fields: List[str]):
    fields = {
        field_name: (field.annotation, field)
        for field_name, field in base.model_fields.items()
        if field_name not in exclude_fields
    }
    model_name = base.__name__ + "_" + random.choices(string.ascii_lowercase, k=6)()
    return create_model(model_name, **fields, __config__=base.model_config)


class SubClassModel(omit_model_fields(MyModel, ["sec_id"])):
    another_id: Optional[List[PydanticObjectId]] = Field(default=None)
```

**Comment by ShravanSunder** [comment]
i've expanded my approach methoned above.  EntityBaseModel can be any BaseModel.  Basically it automatics creating subsets allowing you to just mention keys.  You can override model validators etc, but thats not necessary.  

```py
# this is how its used
DescriptionSubsetFieldNames: t.TypeAlias = t.Literal["description", "tags"]
descriptionSubsetConfig: t.Dict[DescriptionSubsetFieldNames, ExtraSubsetFieldInfo] = {}

subset = create_model_subset(
      model_name="AgentToolDescriptionSubset",
      original_base_model=cls,
      include_field_config=descriptionSubsetConfig,
      model_validators=[
        cls.validate_description_subset,
      ],
    )
    return subset
```


```py
# this is the definiton of the helper funciton to create subsets from a parent
import copy
import typing as t

from pydantic import BaseModel, create_model, field_validator, model_validator
from pydantic.fields import FieldInfo
from shared.validators.subset_field_info import ExtraSubsetFieldInfo

ValidationMethod: t.TypeAlias = t.Callable[..., t.Any]


def _model_field_definition(base_model_cls: t.Type[BaseModel], field_name: str, field_info: ExtraSubsetFieldInfo) -> tuple[type | None, t.Any]:
  """Get the definition of a model field

  Args:
      base_model_cls (t.Type[BaseModel]): The base model pydantic class
      field_name (str): The name of the field to get the definition for

  Returns:
      tuple[type | None, t.Any]: **field_definitions: Attributes of the new model: <name>=(<type>, <FieldInfo>).
  """
  model_fields = base_model_cls.model_fields

  base_field_info = model_fields[field_name]

  base_field_info.title = field_info.override_title or base_field_info.title
  base_field_info.description = field_info.override_description or base_field_info.description
  base_field_info.examples = field_info.override_examples or base_field_info.examples
  base_field_info.json_schema_extra = field_info.override_json_schema_extra or base_field_info.json_schema_extra

  if field_info.additional_description:
    if base_field_info.description:
      base_field_info.description += "\n"
      base_field_info.description += field_info.additional_description
    else:
      base_field_info.description = field_info.additional_description

  if field_info.additional_examples:
    if base_field_info.examples:
      base_field_info.examples.extend(field_info.additional_examples)
    else:
      base_field_info.examples = field_info.additional_examples

  if field_info.additional_json_schema_extra:
    if base_field_info.json_schema_extra and isinstance(base_field_info.json_schema_extra, dict):
      base_field_info.json_schema_extra.update(field_info.additional_json_schema_extra)
    elif callable(base_field_info.json_schema_extra):
      base_field_info.json_schema_extra(field_info.additional_json_schema_extra)
    else:
      base_field_info.json_schema_extra = field_info.additional_json_schema_extra

  return (base_field_info.annotation, base_field_info)


def create_model_subset[TFieldNames: str](
  model_name: str,
  original_base_model: t.Type[BaseModel],
  include_field_config: dict[TFieldNames, ExtraSubsetFieldInfo],
  *,
  model_validators: t.List[ValidationMethod],
) -> t.Type[BaseModel]:
  """Get a subset of model fields"""
  from agent_store.common.models.entity_base_model import EntityBaseModel
  # you dont need to use this base class, can be ignored its for my own purposes.  Just replace with BaseModel or remove

  original_model_cls = copy.deepcopy(original_base_model)

  validators: t.Dict[str, t.Any] = {}
  field_definitions: t.Dict[str, t.Tuple[type | None, FieldInfo]] = {}
  for field_name, extra_field_info in include_field_config.items():
    field_definitions[field_name] = _model_field_definition(original_model_cls, field_name, extra_field_info)

    for v in extra_field_info.field_validators:
      validators[v.validator.__name__] = field_validator(field_name, mode=v.mode)(v.validator)

    if model_validators:
      for v in model_validators:
        fn = model_validator(mode="after")(v)
        validators[v.__name__] = fn

  base = copy.deepcopy(EntityBaseModel)
  base.model_config["extra"] = "ignore"

  new_model_cls = create_model(
    model_name,
    __doc__=original_model_cls.__doc__,
    __module__=original_model_cls.__module__,
    __base__=EntityBaseModel,
    __validators__=validators,  # pyright: ignore [reportGeneralTypeIssues]
    **field_definitions,  # pyright: ignore [reportGeneralTypeIssues]
  )

  return new_model_cls  # pyright: ignore [reportUnknownVariableType]

```

```
# data classes to pass vars around
import typing as t
from dataclasses import dataclass, field

from pydantic.config import JsonValue
from pydantic.functional_validators import FieldValidatorModes

ValidationMethod: t.TypeAlias = t.Callable[..., t.Any]


@dataclass()
class SubsetValidator:
  validator: ValidationMethod
  mode: FieldValidatorModes


@dataclass
class ExtraSubsetFieldInfo:
  field_validators: t.List[SubsetValidator] = field(default_factory=list)

  additional_json_schema_extra: t.Dict[str, JsonValue] = field(default_factory=dict)
  additional_description: str = field(default="")
  additional_examples: t.List[t.Any] = field(default_factory=list)

  override_title: str | None = field(default=None)
  override_description: str | None = field(default=None)
  override_examples: t.List[t.Any] | None = field(default=None)
  override_json_schema_extra: t.Dict[str, JsonValue] | None = field(default=None)

```

in my case i wanted to have additional control over json schema generation etc

**Comment by shurshilov** [comment]
I think i found solution
I use like this
```
from pydantic import BaseModel
from ...utils.pydantic_types import OmitId, Partial


class SchemaUser(BaseModel, extra="forbid"):
    id: int
    name: str
    email: str
    password_hash: str


# Partial<Post> & Omit<Post, 'id'>>
class SchemaUserUpdate(SchemaUser, Partial, OmitId): ...


# Omit<Post, 'id'>
class SchemaUserCreate(SchemaUser, OmitId): ...
```



```
from typing import Any, Type, Union

from pydantic import BaseModel
from pydantic_core import PydanticUndefined


class Partial(BaseModel):
    @classmethod
    def __pydantic_init_subclass__(cls, **kwargs: Any) -> None:
        super().__pydantic_init_subclass__(**kwargs)

        for name, field in list(cls.model_fields.items()):
            if field.is_required():
                field.default = None
                field.annotation = Union[field.annotation, type(None)]

        cls.model_rebuild(force=True)


class OmitId(BaseModel):
    @classmethod
    def __pydantic_init_subclass__(cls, **kwargs: Any) -> None:
        super().__pydantic_init_subclass__(**kwargs)

        for name, field in list(cls.model_fields.items()):
            if name == "id":
                field.default = PydanticUndefined
                del cls.model_fields[name]

        cls.model_rebuild(force=True)
```

**Comment by sydney-runkle** [comment]
This requires more work than fits in the scope of v2.11 :(.

**Comment by StoneSteel27** [comment]
I have built an module to handle this issue, as this was crucial for developing removable parts of an context history of an AI agent, That I was building : https://github.com/StoneSteel27/pydantic-pick

Here is an example:
```py
from pydantic import BaseModel
from pydantic_pick import create_subset

class Profile(BaseModel):
    avatar_url: str
    billing_secret: str  # We want to drop this

class DBUser(BaseModel):
    id: int
    username: str
    password_hash: str  # And drop this
    profiles: list[Profile]

    def check_password(self, guess: str) -> bool:
        # This method relies on password_hash
        return self.password_hash == guess

# Create a subset using dot-notation to drill into nested lists
PublicUser = create_subset(
    DBUser, 
    ("id", "username", "profiles.avatar_url"), 
    "PublicUser"
)

user = PublicUser(id=1, username="alice", profiles=[{"avatar_url": "img.png"}])

# Because password_hash was omitted, AST parsing automatically drops check_password
# Calling user.check_password("secret") will raise a custom AttributeError 
# explaining it was intentionally omitted during extraction
```

It can handle most types like Union, Enums, List, Dict, Set, Tuple, Literals, Annotated. And also handles Field, constants, ClassVars.
It will take care of class based wrappers, function based wrappers with AST parsing. this means, `@computed_fields` and validators are handled

If you have any issues, please feel free to raise in my repo
