### ISSUE TITLE
Mypy regression - Missing named argument

### ISSUE THREAD

**Issue by pykler** [pydantic/pydantic#5190]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

pydantic version 1.10.6 + mypy 1.1.1 + mypy plugin causes error with previously ok code.
Note: mypy plugin is irrelevant, and does not affect the output in this usecase

Using Field with a description on an optional Field, without an explicit default=None, used to work

```
$ mypy sample.py 
sample.py:10: error: Missing named argument "bar" for "Sample"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```
Error started happening with pydantic 1.10.4, version 1.10.2 does not have this issue
versions >1.10.2 now require the explicit default=None on Optional fields.

This seems like a bug, if not please advise.

### Example Code

```Python
from typing import Optional
from pydantic import BaseModel, Field


class Sample(BaseModel):
    foo: str
    bar: Optional[str] = Field(description="optional")


Sample(foo="hello world")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.6
            pydantic compiled: True
                 install path: /home/hatem/projects/inventory_service/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0]
                     platform: Linux-5.11.0-37-generic-x86_64-with-glibc2.29
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
This appears to have been introduced by using `@dataclass_transform` on the metaclass, and the reason that it works in 1.10.2 is because that version used the keyword argument `field_descriptors` instead of the correct `field_specifiers`.

I'm not sure how involved it will be to fix this properly while retaining the `@dataclass_transform` behavior; the good news is that in v2 this shouldn't be an issue because we no longer set an implicit default for Optional/Any fields.

Does anyone know why the keyword argument was `field_descriptors` before? Was that just a typo?

**Comment by dmontagu** [comment]
Seems there was some logic issues in the plugin that meant it wouldn't work correctly if you set a `Field` as the default but didn't specify `default` or `default_factory`. The `dataclass_transform` thing was just hiding the issue. I've got a fix coming shortly.

**Comment by HiromuHota** [comment]
This issue is present in v2.
For example, pydantic-2.11.7 pydantic-core-2.33.2 give the same issue.
```
Successfully installed pydantic-2.11.7 pydantic-core-2.33.2
# mypy sample.py 
sample.py:10: error: Missing named argument "bar" for "Sample"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

mypy == 1.1.1

Update: is this not applicable to v2?
According to https://docs.pydantic.dev/latest/concepts/fields/#default-values, 
> [In Pydantic V1](https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields), a type annotated as [Any](https://docs.python.org/3/library/typing.html#typing.Any) or wrapped by [Optional](https://docs.python.org/3/library/typing.html#typing.Optional) would be given an implicit default of None even if no default was explicitly specified. This is no longer the case in Pydantic V2.
